<%@ Page Title="" Language="C#" MasterPageFile="~/Master2.Master" AutoEventWireup="true" CodeBehind="AdminView.aspx.cs" Inherits="CheapShop.AdminView" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MasContent2" runat="server">
    

    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="age" HeaderText="age" SortExpression="age" />
                <asp:BoundField DataField="contactNo" HeaderText="contactNo" SortExpression="contactNo" />
                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                <asp:BoundField DataField="userName" HeaderText="userName" SortExpression="userName" />
                <asp:BoundField DataField="password" HeaderText="password" SortExpression="password" />
            </Columns>
        </asp:GridView>

        <asp:Button  ID="backToAdminHome" runat="server" Text="Admin Home" OnClick="backToAdminHome_Click"/>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:MaintabConnectionString %>" 
            SelectCommand="SELECT * FROM [Registration]"
            UpdateCommand="Update [Registration] Set [name]=@name, [age]=@age,[contactNo]=@contactNo,[email]=@email,[address]=@address,[userName]=@userName,[password]=@password where [Id]=@Id"
            DeleteCommand="Delete From [Registration] where [Id]=@id"
            ></asp:SqlDataSource>
    </form>
    

</asp:Content>
